# Change these first
owner: cfsausgit # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CFS Website
    url: https://www.cfs-australasia.com
  - name: Front End (API Server)
    url: $CONNECT
  - name: URL Shortener
    url: $SHORTENER
  - name: Snap Webhost
    url: $SURVEYS
  - name: Survey To Go
    url: $STG
  - name: Grafana
    url: $GRAFANA
  - name: Argo
    url: $ARGO
#   - name: Airflow
#     url: $AIRFLOW
  - name: Audit Angels Plus AV - Test
    url: $AV_TEST
  - name: Audit Angels Plus AV - Prod
    url: $AV_PROD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cfs-australasia.com
  # baseUrl: /your-repo-name
  theme: ocean
  favicon: https://www.cfs-australasia.com/wp-content/uploads/2020/04/favicon-32x32-1.png
  logoUrl: https://www.cfs-australasia.com/wp-content/uploads/2016/09/cfs-header-150.png
  name: Status
  introTitle: "**CFS Australasia** Status page"
  introMessage: This page provides **real-time** status updates for CFS Australasia public endpoints
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
i18n:
  footer: CFS Australasia
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
